---
# Logging configuration
logging:
  level: INFO
  loggers:
    com.radar.stock: DEBUG

# Email notification settings
email:
  # SMTP server settings (Gmail by default)
  host: "smtp.gmail.com"
  port: 587
  enableTLS: true
  enableSSL: false
  
  # List of email addresses to notify
  recipients:
    - "nayanmee55@gmail.com"
    - "manionicra54@gmail.com"
  
  # Sender display name
  senderName: "Amul Stock Radar"
  
  # Enable/disable email notifications
  enabled: true

# Product monitoring (optional)
# Uncomment to monitor only specific products
# watchedProducts:
#   - "amul-protein-buttermilk-200ml"
#   - "amul-high-protein-lassi-250ml"
